app = "ani-subs"
primary_region = "hkg"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
APP_ENV = "production"
DATABASE_URL = "postgres://postgres:${POSTGRES_PASSWORD}@ani-postgres.internal:5432/newsletter"
TZ = "Asia/Shanghai"

[[services]]
internal_port = 8000
protocol = "tcp"

[[services.ports]]
port = 8000
[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"
memory_mb = 1_024