app = "ani-subs"
primary_region = "hkg"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
APP_ENV = "production"
DB_HOST = "ani-postgres.internal"
DB_PORT = "5432"
DB_NAME = "newsletter"
DB_USERNAME = "postgres"
DB_REQUIRE_SSL = "false"
TZ = "Asia/Shanghai"

[[services]]
internal_port = 8000
protocol = "tcp"

[[services.ports]]
port = 8000
[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"
memory_mb = 1_024