app = "ani-subs"
primary_region = "hkg"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
APP_ENV = "production"
DB_HOST = "ani-postgres.internal"
DB_PORT = "5432"
DB_NAME = "newsletter"
DB_USERNAME = "postgres"
DB_REQUIRE_SSL = "false"
TZ = "Asia/Shanghai"

[[services]]
internal_port = 8000
protocol = "tcp"

# 使用 Fly 的 HTTP/HTTPS 代理
[[services.ports]]
port = 80
handlers = ["http"]  # HTTP 流量

[[services.ports]]
port = 443
handlers = ["tls", "http"]  # HTTPS 流量

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = 512
memory_mb = 512