application:
  port: 8000
  host: 0.0.0.0
database:
  host: "127.0.0.1" # 如果是docker Compose, 使用服务名称 postgresql, 否则使用实际的IP地址或域名
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
  require_ssl: false
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  authorization_token: "my-secret-token"
token:
  access_token: 20 # mins
  refresh_token: 15 # days